<?xml version="1.0" encoding="utf-8"?><Database Name="OrganizedEndeavors" Class="OrganizedEndeavorsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=OrganizedEndeavors;Integrated Security=True" SettingsObjectName="OrganizedEndeavors.Data.Properties.Settings" SettingsPropertyName="OrganizedEndeavorsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Endeavors" Member="Endeavors">
    <Type Name="Endeavor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Endeavor" Member="Endeavor1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="HandledBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Member_Endeavor" Member="Member" ThisKey="HandledBy" OtherKey="Id" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Members" Member="Members">
    <Type Name="Member">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Member_Endeavor" Member="Endeavors" ThisKey="Id" OtherKey="HandledBy" Type="Endeavor" />
    </Type>
  </Table>
</Database>